# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 07d6bea1bea4fedb264460abec45a5379cf430f4c99e96930391abc5b23f1b67a41d7e1de0ef1e342ab50e5c384b433ea4f50baa5b0ab85211b21256682c3172

test:
  secret_key_base: d81e8e5823a9a30655625e7588d95bd79a3783b95b3ee17e696d53b88220569ca4860b6f72b090f80d44358a6d0a3a1f803bf9086461d8c0a97c8ffe7a186b92

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
